// This is a placeholder file for local development.
// The real aws-exports.js file will be generated by the Amplify CLI.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": []
};

export default awsmobile;
